project:
  type: website
  title: "GD benchmark sets"
  preview:
    browser: true
    watch-inputs: true

website:
  title: "GD benchmark sets"

format:
  html:
    theme: lumen
    toc: true

number-sections: true
number-depth: 2

editor:
  render-on-save: true
