project:
  type: website
  title: "GD benchmark sets"

website:
  title: "GD benchmark sets"

format:
  html:
    theme: lumen
    toc: true

number-sections: true
number-depth: 2

editor:
  render-on-save: true

execute:
  freeze: auto
